service: p1s3-web-requests
runtime: python37
entrypoint: uwsgi --http-socket :8080 --wsgi-file boots_main.py --callable app --master --processes 1 --threads 2

handlers:
- url: /p1s3/.*
  script: auto
  secure: always

vpc_access_connector:
  name: "projects/aqueous-choir-160420/locations/us-central1/connectors/redis"
